verbosity = 2

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"
[language.rust.settings]
diagnostics.disabled = ["unresolved-proc-macro"]

[language.javascript]
filetypes = ["javascript"]
roots = [".flowconfig"]
command = "flow"
args = ["lsp"]

[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", "pyproject.toml"]
command = "jedi-language-server"

[language.go]
filetypes = ["go"]
roots = ["go.mod"]
command = "gopls"
args = ["serve"]

[language.dart]
filetypes = ["dart"]
roots = ["pubspec.yaml"]
command = "dart"
args = ["/opt/dart-sdk/bin/snapshots/analysis_server.dart.snapshot", "--lsp"]

[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]
