[package]
authors = ["Dimitri Merejkowsky <dimitri.merejkowsky@tanker.io>"]
edition = "2018"
name = "bwataout"
version = "0.1.0"

[dependencies]
anyhow = "1.0.31"
app_dirs = "1.2.1"
clipboard = "0.5.0"
rusqlite = "0.25.3"
structopt = "*"

[dev-dependencies]
tempdir = "0.3.7"
