[package]
authors = ["Dimitri Merejkowsky <dimitri.merejkowsky@tanker.io>"]
edition = "2021"
name = "bwataout"
version = "0.1.0"

[dependencies]
anyhow = "1.0.31"
clipboard = "0.5.0"
directories = "4.0"
rusqlite = "0.25.3"
serde = { version = "1.0", features = ["derive"] }
structopt = "*"
toml = "0.5"

[dev-dependencies]
tempdir = "0.3.7"
