""" Install the dot files """

from __future__ import print_function

import os

THIS_DIR = os.path.abspath(os.path.dirname(__file__))

def mkdir_p(path):
    if not os.path.exists(path):
        os.makedirs(path)

def create_symlink_if_missing(src, dest):
    if os.path.exists(src):
        print("Skipping", src)
        return
    dirname = os.path.dirname(src)
    mkdir_p(dirname)
    print(src, "->", dest)
    os.symlink(dest, src)

def write_file_if_missing(path, contents):
    if os.path.exists(path):
        print("Skipping", path)
        return
    print("Creating", path)
    dirname = os.path.dirname(path)
    mkdir_p(dirname)
    with open(path, "w") as fp:
        fp.write(contents)

def main():
    mkdir_p(os.path.expanduser("~/.local/bin"))
    mkdir_p(os.path.expanduser("~/.config"))

    # .gitconfig
    gitconfig = os.path.expanduser("~/.config/git/config")
    write_file_if_missing(gitconfig, """\
# Autogenerated. Do not edit
[core]
excludesfile = {0}/gitexcludes

[include]
path = {0}/gitconfig
path = {0}/gitconfig.local


""" .format(THIS_DIR))

    # .zsh
    zshrc = os.path.expanduser("~/.zshrc")
    write_file_if_missing(zshrc, """\
# Auto-generated. Do not edit
# Customization go into {0}/zshrc.local
source {0}/zshrc
if [ -f {0}/zshrc.local ] ; then
  source {0}/zshrc.local
fi
""".format(THIS_DIR))

    # conky
    src = os.path.expanduser("~/.config/conky/conky.conf")
    dest = os.path.join(THIS_DIR, "conky.conf")
    create_symlink_if_missing(src, dest)

    # screen
    src = os.path.expanduser("~/.screenrc")
    dest = os.path.join(THIS_DIR, "screenrc")
    create_symlink_if_missing(src, dest)


if __name__ == "__main__":
    main()
