global = [
    "AUTH",
    "Awaitable",
    "Backend",
    "Baz",
    "CHANGELOG",
    "CONFIG",
    "CORS",
    "Callsite",
    "Cli",
    "Config",
    "Dimitri",
    "Dirs",
    "HEXA",
    "HOSTNAME",
    "Http",
    "IDENT",
    "Init",
    "JSON",
    "LINENO",
    "Linters",
    "MERCHANTABILITY",
    "Merejkowsky",
    "Ok",
    "PATHNAME",
    "POSTGRES",
    "PYTHONPATH",
    "Postgre",
    "Postgres",
    "README",
    "Redistributions",
    "Renderer",
    "SSL",
    "Sqlite",
    "Subfolders",
    "Substring",
    "TODO",
    "Tmux",
    "UI",
    "UTF",
    "UUID",
    "Uncomment",
    "Whitespace",
    "XDG",
    "ada",
    "algo",
    "api",
    "arg",
    "args",
    "auth",
    "backend",
    "backends",
    "balancer",
    "baz",
    "bool",
    "cd",
    "changelog",
    "chrono",
    "ci",
    "cli",
    "cmd",
    "concat",
    "config",
    "cpp",
    "darwin",
    "desc",
    "dev",
    "devs",
    "dir",
    "dirs",
    "enum",
    "env",
    "environ",
    "favicon",
    "fileobj",
    "filesystem",
    "fs",
    "github",
    "gitignore",
    "goto",
    "homebrew",
    "hostname",
    "http",
    "ico",
    "ini",
    "init",
    "io",
    "js",
    "json",
    "latin",
    "lineno",
    "linux",
    "lossy",
    "md",
    "middleware",
    "mkdir",
    "msvc",
    "num",
    "ok",
    "orm",
    "param",
    "params",
    "pc",
    "postgres",
    "postgresql",
    "pre",
    "prepended",
    "pubsub",
    "py",
    "readme",
    "redis",
    "repo",
    "ripgrep",
    "semver",
    "sha",
    "sqlalchemy",
    "src",
    "ssl",
    "stdin",
    "stdout",
    "struct",
    "subdir",
    "subpath",
    "substring",
    "svg",
    "tempdir",
    "textwrap",
    "tmp",
    "tmux",
    "toml",
    "travis",
    "tty",
    "txt",
    "unicode",
    "unix",
    "untyped",
    "upstream's",
    "url",
    "urls",
    "utc",
    "utf",
    "uuid",
    "vec",
    "venv",
    "wget",
    "whitespace",
    "xlsx",
]

[extensions]
kak = [
    "Buf",
    "Gl",
    "fi",
    "gi",
    "params",
    "printf",
    "pwd",
    "str",
]
py = [
    "Enum",
    "Popen",
    "abc",
    "abstractmethod",
    "abstractproperty",
    "args",
    "argv",
    "async",
    "attr",
    "autouse",
    "breakpoint",
    "cls",
    "conftest",
    "contextvars",
    "copyfileobj",
    "dataclass",
    "dataclasses",
    "datetime",
    "defaultdict",
    "del",
    "dicts",
    "elif",
    "endswith",
    "env",
    "exc",
    "fetchall",
    "figsize",
    "fmt",
    "fromtimestamp",
    "getenv",
    "isinstance",
    "isoformat",
    "issubset",
    "iterdir",
    "itertools",
    "len",
    "matplotlib",
    "metaclass",
    "mtime",
    "np",
    "os",
    "pathlib",
    "plt",
    "py",
    "pyplot",
    "pytest",
    "rasterio",
    "rb",
    "removeprefix",
    "repr",
    "sep",
    "shutil",
    "skipif",
    "splitlines",
    "sqlite",
    "startswith",
    "stdout",
    "str",
    "subprocess",
    "sys",
    "tablename",
    "textwrap",
    "tomllib",
    "tz",
    "urllib",
    "utcnow",
    "wb",
]
rs = [
    "Bool",
    "Buf",
    "Deque",
    "Deserialize",
    "Eq",
    "Fn",
    "Formatter",
    "Itertools",
    "Mut",
    "Str",
    "Vec",
    "arg",
    "bool",
    "buf",
    "canonicalize",
    "cfg",
    "cmp",
    "const",
    "dbg",
    "de",
    "dedent",
    "deserialize",
    "dyn",
    "enum",
    "eprintln",
    "eq",
    "extern",
    "ffi",
    "fmt",
    "fn",
    "impl",
    "io",
    "iter",
    "len",
    "lt",
    "mut",
    "num",
    "ok",
    "os",
    "pathdiff",
    "pos",
    "println",
    "rsplit",
    "ser",
    "stdin",
    "stdout",
    "str",
    "struct",
    "tt",
    "ty",
    "usize",
]
sh = [
    "chmod",
    "fi",
]
sql = ["BIGINT"]
toml = ["pathdiff"]
